part of '../presentation/editor_application.dart';

enum _HookEditMode { hookWithVideo, bestMoments }

enum _EffectsWorkspaceCategory {
  effects,
  transitions,
  adjustments,
}

const _captionPresets = <_CaptionPreset>[
  _CaptionPreset(
    id: 'capcut',
    name: 'Yellow Focus',
    accentColor: Color(0xfffff000),
    outline: 6,
    shadow: 3,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'big_word_pop',
    name: 'Big Word Pop',
    accentColor: Color(0xffffe500),
    inactiveColor: Colors.white,
    outline: 6,
    shadow: 3,
    motion: 'big_word',
  ),
  _CaptionPreset(
    id: 'orange_pop',
    name: 'Orange Pop',
    accentColor: Color(0xffff8a00),
    outline: 6,
    shadow: 3,
    motion: 'bounce',
  ),
  _CaptionPreset(
    id: 'clean',
    name: 'Clean White',
    accentColor: Colors.white,
    outline: 4,
    shadow: 2,
    uppercase: false,
  ),
  _CaptionPreset(
    id: 'minimal',
    name: 'Minimal',
    accentColor: Colors.white,
    outline: 1.5,
    shadow: 1,
    uppercase: false,
    bold: false,
  ),
  _CaptionPreset(
    id: 'black_box',
    name: 'Black Box',
    accentColor: Colors.white,
    outline: 0,
    shadow: 0,
    backgroundColor: Color(0xcc000000),
    uppercase: false,
    motion: 'box',
  ),
  _CaptionPreset(
    id: 'neon_cyan',
    name: 'Neon Cyan',
    accentColor: Color(0xff00e5ff),
    outlineColor: Color(0xff03242a),
    outline: 5,
    shadow: 5,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'hot_pink',
    name: 'Hot Pink',
    accentColor: Color(0xffff3cac),
    outline: 6,
    shadow: 3,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'lime_punch',
    name: 'Lime Punch',
    accentColor: Color(0xffa3ff12),
    outlineColor: Color(0xff172500),
    outline: 6,
    shadow: 2,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'red_alert',
    name: 'Red Alert',
    accentColor: Color(0xffff3b30),
    outline: 7,
    shadow: 3,
    motion: 'bounce',
  ),
  _CaptionPreset(
    id: 'blue_glow',
    name: 'Blue Glow',
    accentColor: Color(0xff3b82f6),
    outlineColor: Color(0xff061b41),
    outline: 5,
    shadow: 6,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'documentary',
    name: 'Documentary',
    accentColor: Colors.white,
    outline: 2.5,
    shadow: 1,
    uppercase: false,
    bold: false,
    italic: true,
    bottomMargin: 0.07,
  ),
  _CaptionPreset(
    id: 'classic_gold',
    name: 'Classic Gold',
    accentColor: Color(0xffffb000),
    outlineColor: Color(0xff3c2200),
    outline: 5,
    shadow: 4,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'white_impact',
    name: 'White Impact',
    accentColor: Colors.white,
    inactiveColor: Color(0xffb7beca),
    outline: 7,
    shadow: 4,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'cyan_focus',
    name: 'Cyan Focus',
    accentColor: Color(0xff22d3ee),
    outline: 5,
    shadow: 2,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'red_focus',
    name: 'Red Focus',
    accentColor: Color(0xffff2d55),
    outline: 6,
    shadow: 3,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'yellow_box',
    name: 'Yellow Box',
    accentColor: Colors.black,
    inactiveColor: Colors.white,
    activeBoxColor: Color(0xffffe500),
    outline: 0,
    shadow: 0,
    motion: 'box',
  ),
  _CaptionPreset(
    id: 'cyan_box',
    name: 'Cyan Box',
    accentColor: Colors.black,
    inactiveColor: Colors.white,
    activeBoxColor: Color(0xff22d3ee),
    outline: 0,
    shadow: 0,
    motion: 'box',
  ),
  _CaptionPreset(
    id: 'pink_box',
    name: 'Pink Box',
    accentColor: Colors.white,
    inactiveColor: Colors.white,
    activeBoxColor: Color(0xffff2d9a),
    outline: 2,
    shadow: 1,
    motion: 'box',
  ),
  _CaptionPreset(
    id: 'retro_mint',
    name: 'Retro Mint',
    accentColor: Color(0xffff4d67),
    inactiveColor: Color(0xfff7fff8),
    outlineColor: Color(0xff26d9a0),
    outline: 5,
    shadow: 2,
    motion: 'bounce',
  ),
  _CaptionPreset(
    id: 'violet_glow',
    name: 'Violet Glow',
    accentColor: Color(0xffc084fc),
    outlineColor: Color(0xff4c1d95),
    outline: 4,
    shadow: 9,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'sunset_glow',
    name: 'Sunset Glow',
    accentColor: Color(0xffff7a18),
    outlineColor: Color(0xff7c2d12),
    outline: 4,
    shadow: 8,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'ice_glow',
    name: 'Ice Glow',
    accentColor: Color(0xffe0f7ff),
    outlineColor: Color(0xff0284c7),
    outline: 3,
    shadow: 8,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'comic',
    name: 'Comic Punch',
    accentColor: Color(0xfffff200),
    inactiveColor: Colors.white,
    outline: 8,
    shadow: 5,
    motion: 'bounce',
  ),
  _CaptionPreset(
    id: 'typewriter',
    name: 'Typewriter',
    accentColor: Colors.white,
    inactiveColor: Color(0xff707784),
    outline: 1,
    shadow: 1,
    uppercase: false,
    bold: false,
    motion: 'highlight',
  ),
  _CaptionPreset(
    id: 'purple_split',
    name: 'Purple Split',
    accentColor: Color(0xffe879f9),
    inactiveColor: Color(0xffc4b5fd),
    outlineColor: Color(0xff3b0764),
    outline: 5,
    shadow: 3,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'aqua_split',
    name: 'Aqua Split',
    accentColor: Color(0xff2dd4bf),
    inactiveColor: Color(0xffe0f2fe),
    outlineColor: Color(0xff042f2e),
    outline: 5,
    shadow: 3,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'orange_box',
    name: 'Orange Box',
    accentColor: Colors.black,
    inactiveColor: Colors.white,
    activeBoxColor: Color(0xffff8a00),
    outline: 0,
    shadow: 0,
    motion: 'box',
  ),
  _CaptionPreset(
    id: 'soft_purple',
    name: 'Soft Purple',
    accentColor: Color(0xfff0abfc),
    inactiveColor: Colors.white,
    outlineColor: Color(0xff581c87),
    outline: 3,
    shadow: 4,
    uppercase: false,
    motion: 'glow',
  ),
  _CaptionPreset(
    id: 'news_lower',
    name: 'News Lower',
    accentColor: Color(0xffffd400),
    inactiveColor: Colors.white,
    backgroundColor: Color(0xcc111827),
    outline: 0,
    shadow: 0,
    uppercase: false,
    bottomMargin: 0.06,
    motion: 'highlight',
  ),
  _CaptionPreset(
    id: 'mono_focus',
    name: 'Mono Focus',
    accentColor: Colors.white,
    inactiveColor: Color(0xff6b7280),
    outline: 3,
    shadow: 2,
    motion: 'pop',
  ),
  _CaptionPreset(
    id: 'gold_box',
    name: 'Gold Box',
    accentColor: Color(0xff271600),
    inactiveColor: Colors.white,
    activeBoxColor: Color(0xffffc928),
    outline: 0,
    shadow: 1,
    motion: 'box',
  ),
];

enum _EditorShortcut {
  export,
  saveProject,
  openProject,
  split,
  cutStart,
  cutEnd,
  undo,
  redo,
  playPause,
  deletePart,
  copy,
  cut,
  paste,
  duplicate,
}

enum _TimelineClipAction {
  copy,
  cut,
  paste,
  duplicate,
  copyAttributes,
  pasteAttributes,
  split,
  delete,
  captions,
  extractAudio,
  effects,
  transitions,
  deactivate,
  details,
}
