part of 'capcut_draft_service.dart';

Map<String, Object?> _textMaterial({
  required String id,
  required String text,
  required String font,
  required double fontSize,
  required String color,
  required double opacity,
  required bool bold,
  required bool italic,
  required bool underline,
  required String strokeColor,
  required double strokeWidth,
  required bool shadow,
  required double tracking,
  required double lineSpacing,
  bool isCaption = false,
}) {
  final draftFontSize = isCaption
      ? _capCutDraftCaptionFontSize(fontSize)
      : _capCutDraftTextFontSize(fontSize);
  final content = {
    'text': text,
    'styles': [
      {
        'range': [0, text.length],
        'size': draftFontSize,
        'font': font,
        'fill': {
          'alpha': opacity.clamp(0.0, 1.0),
          'content': {
            'render_type': 'solid',
            'solid': {
              'alpha': opacity.clamp(0.0, 1.0),
              'color': _capCutColor(color),
            },
          },
        },
      }
    ],
  };
  return {
    'add_type': 0,
    'alignment': 1,
    'autoAdaptCanvasEnabled': false,
    'base_content': '',
    'background_alpha': 0.0,
    'background_color': '',
    'background_fill': '',
    'background_height': 0.14,
    'background_horizontal_offset': 0.0,
    'background_round_radius': 0.0,
    'background_style': 0,
    'background_vertical_offset': 0.0,
    'background_width': 0.14,
    'bold_width': bold ? 0.08 : 0.0,
    'border_alpha': 1.0,
    'border_color': strokeColor,
    'border_mode': 0,
    'border_width': strokeWidth <= 0 ? 0.0 : strokeWidth / 100,
    'caption_template_info': {
      'resource_id': '',
      'third_resource_id': '',
      'resource_name': '',
      'category_id': '',
      'category_name': '',
      'effect_id': '',
      'request_id': '',
      'path': '',
      'is_new': false,
      'source_platform': 0,
    },
    'check_flag': 7,
    'combo_info': {'text_templates': []},
    'content': jsonEncode(content),
    'current_words': {
      'start_time': [],
      'end_time': [],
      'text': [],
    },
    'cutoff_postfix': '',
    'enable_path_typesetting': false,
    'fixed_height': -1.0,
    'fixed_width': -1.0,
    'font_category_id': '',
    'font_category_name': '',
    'font_id': '',
    'font_name': font,
    'font_path': '',
    'font_resource_id': '',
    'font_source_platform': 0,
    'font_team_id': '',
    'font_third_resource_id': '',
    'font_size': draftFontSize,
    'font_title': font,
    'font_url': '',
    'fonts': [],
    'force_apply_line_max_width': false,
    'global_alpha': opacity.clamp(0.0, 1.0),
    'group_id': '',
    'has_shadow': shadow,
    'id': id,
    'initial_scale': 1.0,
    'inner_padding': -1.0,
    'is_batch_replace': false,
    'is_lyric_effect': false,
    'is_rich_text': false,
    'is_words_linear': false,
    'italic_degree': italic ? 10 : 0,
    'ktv_color': '',
    'language': '',
    'layer_weight': 0,
    'letter_spacing': tracking,
    'line_feed': 1,
    'line_max_width': 0.82,
    'line_spacing': lineSpacing,
    'lyric_group_id': '',
    'lyrics_template': {
      'resource_id': '',
      'resource_name': '',
      'panel': '',
      'effect_id': '',
      'path': '',
      'category_id': '',
      'category_name': '',
      'request_id': '',
    },
    'multi_language_current': 'none',
    'name': text.length > 40 ? '${text.substring(0, 40)}...' : text,
    'offset_on_path': 0.0,
    'oneline_cutoff': false,
    'operation_type': 0,
    'original_size': [],
    'preset_category': '',
    'preset_category_id': '',
    'preset_has_set_alignment': false,
    'preset_id': '',
    'preset_index': 0,
    'preset_name': '',
    'punc_model': '',
    'recognize_model': '',
    'recognize_task_id': '',
    'recognize_text': '',
    'recognize_type': isCaption ? 1 : 0,
    'relevance_segment': [],
    'shadow_alpha': shadow ? 0.75 : 0.0,
    'shadow_angle': -45.0,
    'shadow_color': '#000000',
    'shadow_distance': shadow ? 5.0 : 0.0,
    'shadow_point': {'x': 0.0, 'y': 0.0},
    'shadow_smoothing': 0.45,
    'shadow_thickness_projection_angle': 0.0,
    'shadow_thickness_projection_distance': 0.0,
    'shadow_thickness_projection_enable': false,
    'shape_clip_x': false,
    'shape_clip_y': false,
    'single_char_bg_alpha': 1.0,
    'single_char_bg_color': '',
    'single_char_bg_enable': false,
    'single_char_bg_height': 0.0,
    'single_char_bg_horizontal_offset': 0.0,
    'single_char_bg_round_radius': 0.3,
    'single_char_bg_vertical_offset': 0.0,
    'single_char_bg_width': 0.0,
    'source_from': '',
    'ssml_content': '',
    'style_name': '',
    'sub_type': isCaption ? 1 : 0,
    'sub_template_id': -1,
    'subtitle_keywords': null,
    'subtitle_keywords_config': null,
    'subtitle_template_original_fontsize': isCaption ? draftFontSize : 0.0,
    'text_alpha': opacity.clamp(0.0, 1.0),
    'text_color': color,
    'text_curve': null,
    'text_exceeds_path_process_type': 0,
    'text_loop_on_path': false,
    'text_preset_resource_id': '',
    'text_size': draftFontSize,
    'text_to_audio_ids': [],
    'text_typesetting_path_index': 0,
    'text_typesetting_paths': null,
    'text_typesetting_paths_file': '',
    'translate_original_text': '',
    'tts_auto_update': false,
    'type': 'text',
    'typesetting': 0,
    'underline': underline,
    'underline_offset': 0.22,
    'underline_width': 0.05,
    'use_effect_default_color': false,
    'words': {
      'start_time': [],
      'end_time': [],
      'text': [],
    },
  };
}

Map<String, Object?> _textSegment({
  required String materialId,
  required int targetStartUs,
  required int targetDurationUs,
  required double x,
  required double y,
  required int renderIndex,
  bool isCaption = false,
}) {
  final segmentId = _uuid();
  return {
    'caption_info': isCaption
        ? {
            'type': 'subtitle',
            'fragment_info': null,
            'fragment_duration': 0,
            'anims_info': null,
            'keywords_style': '',
            'keyword_extra_style': {
              'keyword_capital': '',
              'keyword_supersize': 1.0,
              'keyword_isolation': '',
              'keyword_isolation_supersize': 1.0,
              'style_unbundling': [],
            },
            'capital': '',
            'modify_info': null,
          }
        : null,
    'cartoon': false,
    'clip': {
      'alpha': 1.0,
      'flip': {'horizontal': false, 'vertical': false},
      'rotation': 0.0,
      'scale': {'x': 1.0, 'y': 1.0},
      'transform': {'x': x, 'y': y},
    },
    'common_keyframes': [],
    'enable_adjust': false,
    'enable_adjust_mask': false,
    'enable_color_adjust_pro': false,
    'enable_color_correct_adjust': false,
    'enable_color_curves': true,
    'enable_color_match_adjust': false,
    'enable_color_wheels': true,
    'enable_hsl': false,
    'enable_hsl_curves': true,
    'enable_lut': false,
    'enable_mask_shadow': false,
    'enable_mask_stroke': false,
    'enable_smart_color_adjust': false,
    'enable_video_mask': true,
    'extra_material_refs': [],
    'group_id': '',
    'hdr_settings': null,
    'id': segmentId,
    'intensifies_audio': false,
    'is_loop': false,
    'is_placeholder': false,
    'is_tone_modify': false,
    'keyframe_refs': [],
    'last_nonzero_volume': 1.0,
    'lyric_keyframes': null,
    'material_id': materialId,
    'raw_segment_id': '',
    'render_index': renderIndex,
    'render_timerange': {'duration': 0, 'start': 0},
    'responsive_layout': {
      'enable': false,
      'horizontal_pos_layout': 0,
      'size_layout': 0,
      'target_follow': '',
      'vertical_pos_layout': 0,
    },
    'reverse': false,
    'segment_color_tag': '',
    'source': 'segmentsourcenormal',
    'source_timerange': null,
    'speed': 1.0,
    'state': 0,
    'target_timerange': {'duration': targetDurationUs, 'start': targetStartUs},
    'template_id': '',
    'template_scene': 'default',
    'track_attribute': 0,
    'track_render_index': 0,
    'uniform_scale': {'on': true, 'value': 1.0},
    'visible': true,
    'volume': 1.0,
  };
}

Map<String, Object?> _draftMeta({
  required String id,
  required String name,
  required String folder,
  required String root,
  required int durationUs,
  required List<Map<String, Object?>> materials,
  required int nowUs,
}) {
  return {
    'cloud_draft_cover': false,
    'cloud_draft_sync': false,
    'draft_cloud_template_id': '',
    'draft_cover': '',
    'draft_enterprise_info': {
      'draft_enterprise_extra': '',
      'draft_enterprise_id': '',
      'draft_enterprise_name': '',
      'enterprise_material': [],
    },
    'draft_fold_path': _jsonPath(folder),
    'draft_id': id,
    'draft_is_ai_packaging_used': false,
    'draft_is_ai_shorts': false,
    'draft_is_cloud_temp_draft': false,
    'draft_is_invisible': false,
    'draft_materials': [
      {'type': 0, 'value': materials},
      {'type': 1, 'value': []},
      {'type': 2, 'value': []},
      {'type': 3, 'value': []},
      {'type': 6, 'value': []},
      {'type': 7, 'value': []},
    ],
    'draft_materials_copied_info': [],
    'draft_name': name,
    'draft_new_version': '',
    'draft_root_path': _jsonPath(root),
    'draft_segment_extra_info': [],
    'draft_type': '',
    'tm_draft_create': nowUs,
    'tm_draft_modified': nowUs,
    'tm_draft_removed': 0,
    'tm_duration': durationUs,
  };
}

Map<String, Object?> _videoMaterial({
  required String id,
  required String localMaterialId,
  required String path,
  required String name,
  required int durationUs,
  required int width,
  required int height,
  required VideoEditSettings settings,
}) {
  const crop = _CropData(
    ratioName: 'free',
    points: {
      'upper_left_x': 0.0,
      'upper_left_y': 0.0,
      'upper_right_x': 1.0,
      'upper_right_y': 0.0,
      'lower_left_x': 0.0,
      'lower_left_y': 1.0,
      'lower_right_x': 1.0,
      'lower_right_y': 1.0,
    },
  );
  return {
    'id': id,
    'unique_id': '',
    'type': 'video',
    'duration': durationUs,
    'path': path,
    'media_path': '',
    'local_id': '',
    'has_audio': true,
    'reverse_path': '',
    'intensifies_path': '',
    'reverse_intensifies_path': '',
    'intensifies_audio_path': '',
    'cartoon_path': '',
    'width': width,
    'height': height,
    'category_id': '',
    'category_name': 'local',
    'material_id': '',
    'material_name': name,
    'material_url': '',
    'crop': crop.points,
    'crop_ratio': crop.ratioName,
    'audio_fade': null,
    'crop_scale': 1.0,
    'extra_type_option': 0,
    'stable': {
      'stable_level': 0,
      'matrix_path': '',
      'time_range': {'start': 0, 'duration': 0},
    },
    'matting': {
      'flag': 0,
      'path': '',
      'interactiveTime': [],
      'has_use_quick_brush': false,
      'strokes': [],
      'has_use_quick_eraser': false,
      'expansion': 0,
      'feather': 0,
      'reverse': false,
      'custom_matting_id': '',
      'enable_matting_stroke': false,
      'is_clould': false,
      'mask_video_path': '',
      'cloud_product_fps': 0.0,
    },
    'source': 0,
    'source_platform': 0,
    'formula_id': '',
    'check_flag': 62978047,
    'video_algorithm': {'algorithms': [], 'time_range': null, 'path': ''},
    'is_unified_beauty_mode': false,
    'is_set_beauty_mode': false,
    'local_material_id': localMaterialId,
    'origin_material_id': '',
    'request_id': '',
    'has_sound_separated': false,
    'is_text_edit_overdub': false,
    'is_ai_generate_content': false,
    'aigc_type': 'none',
    'is_copyright': false,
    'local_material_from': '',
    'live_photo_timestamp': -1,
    'live_photo_cover_path': '',
    'surface_trackings': [],
  };
}

Map<String, Object?> _videoSegment({
  required String id,
  required String materialId,
  required double speed,
  required int sourceStartUs,
  required int sourceDurationUs,
  required int targetStartUs,
  required int targetDurationUs,
  required int renderIndex,
  required VideoEditSettings settings,
  required List<String> refs,
}) {
  final scaleX = settings.scaleX * settings.zoom;
  final scaleY = settings.scaleY * settings.zoom;
  final uniformScale = (scaleX - scaleY).abs() < 0.001;
  final scaleValue = uniformScale ? scaleX : (scaleX + scaleY) / 2;
  return {
    'caption_info': null,
    'cartoon': false,
    'clip': {
      'alpha': 1.0,
      'flip': {
        'horizontal': settings.flip == 'left' || settings.flip == 'right',
        'vertical': settings.flip == 'down' || settings.flip == 'up',
      },
      'rotation': 0.0,
      'scale': {'x': scaleX, 'y': scaleY},
      'transform': {'x': settings.panX, 'y': settings.panY},
    },
    'color_correct_alg_result': '',
    'common_keyframes': [],
    'desc': '',
    'digital_human_template_group_id': '',
    'enable_adjust': true,
    'enable_adjust_mask': false,
    'enable_color_correct_adjust': false,
    'enable_color_curves': true,
    'enable_color_match_adjust': false,
    'enable_color_wheels': true,
    'enable_hsl': false,
    'enable_hsl_curves': true,
    'enable_lut': true,
    'enable_mask_shadow': false,
    'enable_mask_stroke': false,
    'enable_smart_color_adjust': false,
    'enable_video_mask': true,
    'extra_material_refs': refs,
    'group_id': '',
    'hdr_settings': {'intensity': 1.0, 'mode': 1, 'nits': 1000},
    'id': id,
    'intensifies_audio': false,
    'is_loop': false,
    'is_placeholder': false,
    'is_tone_modify': false,
    'keyframe_refs': [],
    'last_nonzero_volume': settings.originalVolume,
    'lyric_keyframes': null,
    'material_id': materialId,
    'raw_segment_id': '',
    'render_index': renderIndex,
    'render_timerange': {'duration': 0, 'start': 0},
    'responsive_layout': {
      'enable': false,
      'horizontal_pos_layout': 0,
      'size_layout': 0,
      'target_follow': '',
      'vertical_pos_layout': 0,
    },
    'reverse': false,
    'source': 'segmentsourcenormal',
    'source_timerange': {'duration': sourceDurationUs, 'start': sourceStartUs},
    'speed': speed,
    'state': 0,
    'target_timerange': {'duration': targetDurationUs, 'start': targetStartUs},
    'template_id': '',
    'template_scene': 'default',
    'track_attribute': 0,
    'track_render_index': 0,
    'uniform_scale': {'on': uniformScale, 'value': scaleValue},
    'visible': true,
    'volume': settings.originalVolume,
  };
}

_CanvasSize _canvasSize(_MediaInfo media, VideoEditSettings settings) {
  final target = _targetRatio(settings.outputRatio);
  if (target == null) {
    return _CanvasSize(
      width: media.width,
      height: media.height,
      ratioName: 'original',
    );
  }
  final source = media.width / media.height;
  if (source > target) {
    return _CanvasSize(
      width: _even(media.height * target),
      height: _even(media.height.toDouble()),
      ratioName: settings.outputRatio,
    );
  }
  return _CanvasSize(
    width: _even(media.width.toDouble()),
    height: _even(media.width / target),
    ratioName: settings.outputRatio,
  );
}

double? _targetRatio(String ratio) {
  return switch (ratio) {
    '16:9' => 16 / 9,
    '9:16' => 9 / 16,
    '4:5' => 4 / 5,
    '1:1' => 1.0,
    '3:4' => 3 / 4,
    '4:3' => 4 / 3,
    _ => null,
  };
}

int _even(double value) {
  final rounded = value.round();
  return rounded.isEven ? rounded : rounded - 1;
}

Map<String, Object?> _metaMaterial({
  required String id,
  required String path,
  required String name,
  required int durationUs,
  required int width,
  required int height,
  required int nowSec,
  required int nowUs,
  required int type,
  required String metetype,
}) {
  return {
    'ai_group_type': '',
    'create_time': nowSec,
    'duration': durationUs,
    'enter_from': 0,
    'extra_info': name,
    'file_Path': path,
    'height': height,
    'id': id,
    'import_time': nowSec,
    'import_time_ms': nowUs,
    'item_source': 1,
    'md5': '',
    'metetype': metetype,
    'roughcut_time_range': {'duration': durationUs, 'start': 0},
    'sub_time_range': {'duration': -1, 'start': -1},
    'type': type,
    'width': width,
  };
}

Map<String, Object?> _placeholderInfo(String id) => {
      'error_path': '',
      'error_text': '',
      'id': id,
      'meta_type': 'none',
      'res_path': '',
      'res_text': '',
      'type': 'placeholder_info',
    };

Map<String, Object?> _canvas(String id) => {
      'album_image': '',
      'blur': 0.0,
      'color': '',
      'id': id,
      'image': '',
      'image_id': '',
      'image_name': '',
      'source_platform': 0,
      'team_id': '',
      'type': 'canvas_color',
    };

Map<String, Object?> _soundMapping(String id) => {
      'audio_channel_mapping': 0,
      'id': id,
      'is_config_open': false,
      'type': '',
    };

Map<String, Object?> _materialColor(String id) => {
      'gradient_angle': 90.0,
      'gradient_colors': [],
      'gradient_percents': [],
      'height': 0.0,
      'id': id,
      'is_color_clip': false,
      'is_gradient': false,
      'solid_color': '',
      'width': 0.0,
    };

Map<String, Object?> _vocalSeparation(String id) => {
      'choice': 0,
      'enter_from': '',
      'final_algorithm': '',
      'id': id,
      'production_path': '',
      'removed_sounds': [],
      'time_range': null,
      'type': 'vocal_separation',
    };
